version: "3.7"

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    command: ./entrypoint-with-gunicorn.sh
    environment:
      - VARIABLE_TO_CHECK=hey
    env_file:
      - .env
